import { ApolloProvider } from '@apollo/client';
import { ChakraProvider } from '@chakra-ui/react';
import Head from 'next/head';
import client from '../apollo-client';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>My Anime List</title>
        <meta
          name="description"
          content="My anime list app generated by create next app"
        />
        <link ref="icon" href="/favicon.ico" />
      </Head>

      <ApolloProvider client={client}>
        <ChakraProvider>
          <Component {...pageProps} />
        </ChakraProvider>
      </ApolloProvider>
    </>
  );
}

export default MyApp;
