import { ApolloProvider } from '@apollo/client';
import { Global, css } from '@emotion/react';
import styled from '@emotion/styled';
import Head from 'next/head';
import client from '../apollo-client';

// Reset CSS
const GlobalStyles = css`
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  html {
    scroll-behavior: smooth;
  }

  html,
  body {
    height: 100%;
    width: 100%;
  }
`;

const MainSection = styled.main`
  flex-grow: 1;
  margin-top: 80px;
`;

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  min-height: 100vh;
`;

function MyApp({ Component, pageProps }) {
  return (
    <Wrapper>
      <Global styles={GlobalStyles} />
      <Head>
        <title>My Anime List</title>
        <meta
          name="description"
          content="My anime list app generated by create next app"
        />
        <link ref="icon" href="/favicon.ico" />
      </Head>

      <ApolloProvider client={client}>
        <MainSection>
          <Component {...pageProps} />
        </MainSection>
      </ApolloProvider>
    </Wrapper>
  );
}

export default MyApp;
